CREATE TABLE PROFIL
		(ID_PROFIL INT NOT NULL PRIMARY KEY,
		NAME VARCHAR(30) NOT NULL,
		AGE INT NOT NULL,
		GROWTH INT NOT NULL,
		WEIGHT INT NOT NULL,
		SEX VARCHAR(1) NOT NULL,
		GOAL VARCHAR(4) NOT NULL  );

		
CREATE TABLE DIET
		(ID_DIET INT NOT NULL PRIMARY KEY,
		ID_PROFIL INT NOT NULL,
		EATDATE TEXT NOT NULL,
        CONSTRAINT fk_profil
            FOREIGN KEY (ID_PROFIL)
            REFERENCES PROFIL(ID_PROFIL)
			ON DELETE CASCADE
        );


CREATE TABLE PRODUCT
		(ID_PRODUCT INT NOT NULL PRIMARY KEY,
		NAME VARCHAR(40) NOT NULL,
		KCAL INT NOT NULL,
		PROTEIN DECIMAL(3,1) NOT NULL,
		FAT DECIMAL(3,1) NOT NULL,
		CARBS DECIMAL(3,1) NOT NULL,
		FIBER DECIMAL(3,1) NOT NULL
		);


CREATE TABLE MEAL
		(ID_MEAL INT NOT NULL PRIMARY KEY,
		NAME VARCHAR(40) NOT NULL
		);

 
 CREATE TABLE PROFIL_PRODUCT
		(ID_PROFIL INT NOT NULL,
		 ID_PRODUCT INT NOT NULL,
         CONSTRAINT pk_PROFIL_PRODUCT PRIMARY KEY (ID_PROFIL,ID_PRODUCT),
        CONSTRAINT fk_profil_1
            FOREIGN KEY (ID_PROFIL)
            REFERENCES PROFIL(ID_PROFIL)
			ON DELETE CASCADE,
		 CONSTRAINT fk_product_1
            FOREIGN KEY (ID_PRODUCT)
            REFERENCES PRODUCT(ID_PRODUCT)
			ON DELETE CASCADE
         );
 
 
  CREATE TABLE PROFIL_MEAL
		(ID_PROFIL INT NOT NULL,
		 ID_MEAL INT NOT NULL,
         CONSTRAINT pk_PROFIL_MEAL PRIMARY KEY (ID_PROFIL,ID_MEAL),
        CONSTRAINT fk_profil1_2
            FOREIGN KEY (ID_PROFIL)
            REFERENCES PROFIL(ID_PROFIL)
			ON DELETE CASCADE,
		 CONSTRAINT fk_meal_2
            FOREIGN KEY (ID_MEAL)
            REFERENCES MEAL(ID_MEAL)
			ON DELETE CASCADE
         );
 
 
CREATE TABLE DIET_PRODUCT
		(ID_DIET INT NOT NULL,
		 ID_PRODUCT INT NOT NULL,
		 AMOUNT INT NOT NULL,
         CONSTRAINT pk_DIET_PRODUCT PRIMARY KEY (ID_PRODUCT,ID_DIET),
         CONSTRAINT fk_product_3
            FOREIGN KEY (ID_PRODUCT)
            REFERENCES PRODUCT(ID_PRODUCT)
			ON DELETE CASCADE,
         CONSTRAINT fk_diet_3
            FOREIGN KEY (ID_DIET)
            REFERENCES DIET(ID_DIET)
			ON DELETE CASCADE
         );


CREATE TABLE DIET_MEAL
		(ID_DIET INT NOT NULL,
		 ID_MEAL INT NOT NULL,
		 AMOUNT INT NOT NULL,
         CONSTRAINT pk_DIET_MEAL PRIMARY KEY (ID_MEAL,ID_DIET),
         CONSTRAINT fk_meal_4
            FOREIGN KEY (ID_MEAL)
            REFERENCES MEAL(ID_MEAL)
			ON DELETE CASCADE,
         CONSTRAINT fk_diet_4
            FOREIGN KEY (ID_DIET)
            REFERENCES DIET(ID_DIET)
			ON DELETE CASCADE
         );		
	

CREATE TABLE MEAL_PRODUCT
		(ID_MEAL INT NOT NULL,
		 ID_PRODUCT INT NOT NULL,
		 AMOUNT INT NOT NULL,
		 CONSTRAINT pk_MEAL_PRODUCT PRIMARY KEY (ID_MEAL,ID_PRODUCT),
         CONSTRAINT fk_meal_5
            FOREIGN KEY (ID_MEAL)
            REFERENCES MEAL(ID_MEAL)
			ON DELETE CASCADE,
         CONSTRAINT fk_product_5
            FOREIGN KEY (ID_PRODUCT)
            REFERENCES PRODUCT(ID_PRODUCT)
			ON DELETE CASCADE
         );		